# Generated by Django 3.1.1 on 2020-09-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_auto_20200922_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='alias',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
