# Generated by Django 3.1.2 on 2020-10-03 13:07

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_auto_20200928_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='alias',
            field=models.CharField(default=secrets.token_hex, max_length=1000),
        ),
    ]
